import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, LabelList,
} from 'recharts';
import { apiUrl, authHeaders } from '../api/config';
import {
  PageHeader, StatCard, Field, Select, Button, LoadingState, EmptyState, ErrorState,
} from '../components/ui';
import { OPERATORS, OP_LABEL, operatorColor } from '../lib/operators';
import './AnalyticsPage.css';

const OP_OPTIONS = OPERATORS.map((o) => ({ value: o.code, label: o.label }));

const MODES = [
  { id: 'byOperator', label: 'By operator' },
  { id: 'pair', label: 'Operator pair' },
  { id: 'station', label: 'Single station' },
];
const MODE_DESC = {
  byOperator: 'Cross-operator passages and charges generated by every other operator at this operator’s stations.',
  pair: 'Passage count, total charge and the passage list between a station operator and a visiting (tag) operator.',
  station: 'Every passage recorded at one specific toll station in the period.',
};

const ymd = (d) => (d ? d.replace(/-/g, '') : '');
const money = (n) => `€${new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(n) || 0)}`;
const num = (n) => new Intl.NumberFormat('en-US').format(Number(n) || 0);

function toCsv(rows, headers) {
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  return [headers.map(esc).join(','), ...rows.map((r) => headers.map((h) => esc(r[h])).join(','))].join('\n');
}
function downloadCsv(name, csv) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = name;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}

export default function AnalyticsPage() {
  const [mode, setMode] = useState('byOperator');
  const [op, setOp] = useState('NAO');
  const [tagOp, setTagOp] = useState('EG');
  const [stationId, setStationId] = useState('NAO01');
  const [range, setRange] = useState({ from: '2022-01-01', to: '2022-06-30' });
  const [state, setState] = useState({ status: 'idle', data: null, error: '' });
  const didAutoRun = useRef(false);

  const run = async (e) => {
    if (e && e.preventDefault) e.preventDefault();
    if (!range.from || !range.to || range.from > range.to) {
      setState({ status: 'error', data: null, error: 'Choose a valid date range (From must be on or before To).' });
      return;
    }
    setState({ status: 'loading', data: null, error: '' });
    const f = ymd(range.from);
    const t = ymd(range.to);
    let url;
    if (mode === 'byOperator') url = apiUrl(`/chargesBy/${op}/${f}/${t}`);
    else if (mode === 'pair') url = apiUrl(`/passAnalysis/${op}/${tagOp}/${f}/${t}`);
    else url = apiUrl(`/tollStationPasses/${stationId.trim().toUpperCase()}/${f}/${t}`);

    try {
      const res = await fetch(url, { headers: authHeaders() });
      if (res.status === 204) { setState({ status: 'empty', data: null, error: '' }); return; }
      if (res.status === 401) { setState({ status: 'error', data: null, error: 'Your session expired. Please restart the demo.' }); return; }
      const body = await res.json().catch(() => ({}));
      if (!res.ok) {
        setState({ status: 'error', data: null, error: (body && body.error && (body.error.message || body.error)) || 'The request could not be completed.' });
        return;
      }
      setState({ status: 'ready', data: body, error: '' });
    } catch (err) {
      setState({ status: 'error', data: null, error: 'Could not reach the server.' });
    }
  };

  useEffect(() => {
    if (didAutoRun.current) return;
    didAutoRun.current = true;
    run();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const { status, data, error } = state;

  const chart = useMemo(() => {
    if (mode !== 'byOperator' || !data || !Array.isArray(data.vOpList)) return [];
    return data.vOpList
      .map((r) => ({ op: r.visitingOpID, name: OP_LABEL[r.visitingOpID] || r.visitingOpID, passes: Number(r.nPasses) || 0, cost: Number(r.passesCost) || 0 }))
      .sort((a, b) => b.cost - a.cost);
  }, [mode, data]);

  return (
    <>
      <PageHeader
        title="Traffic Analytics"
        subtitle="Passage volumes and inter-operator charges over any period."
      />

      {/* Analysis toolbar */}
      <form className="anx-toolbar" onSubmit={run}>
        <div className="anx-modes" role="group" aria-label="Analysis type">
          {MODES.map((m) => (
            <button
              key={m.id}
              type="button"
              aria-pressed={mode === m.id}
              className={`anx-mode${mode === m.id ? ' is-active' : ''}`}
              onClick={() => { setMode(m.id); setState({ status: 'idle', data: null, error: '' }); }}
            >
              {m.label}
            </button>
          ))}
        </div>

        <div className="anx-controls">
          {mode !== 'station' && (
            <Field label={mode === 'pair' ? 'Station operator' : 'Operator'}>
              <Select value={op} onChange={(e) => setOp(e.target.value)} options={OP_OPTIONS} />
            </Field>
          )}
          {mode === 'pair' && (
            <Field label="Visiting operator">
              <Select value={tagOp} onChange={(e) => setTagOp(e.target.value)} options={OP_OPTIONS} />
            </Field>
          )}
          {mode === 'station' && (
            <Field label="Station ID" hint="e.g. NAO01, AM12">
              <input className="ui-input" value={stationId} onChange={(e) => setStationId(e.target.value)} />
            </Field>
          )}
          <Field label="From">
            <input type="date" className="ui-input" value={range.from} max={range.to}
              onChange={(e) => setRange((r) => ({ ...r, from: e.target.value }))} />
          </Field>
          <Field label="To">
            <input type="date" className="ui-input" value={range.to} min={range.from}
              onChange={(e) => setRange((r) => ({ ...r, to: e.target.value }))} />
          </Field>
          <Button type="submit" loading={status === 'loading'}>
            {status === 'loading' ? 'Running…' : 'Run'}
          </Button>
        </div>
        <p className="anx-mode-desc">{MODE_DESC[mode]}</p>
      </form>

      {/* Results */}
      <div className="anx-results">
        {status === 'idle' && <EmptyState icon="bar-chart" title="Run an analysis" message="Pick a type and a date range, then run." />}
        {status === 'loading' && <LoadingState label="Running analysis…" />}
        {status === 'error' && <ErrorState message={error} onRetry={run} />}
        {status === 'empty' && <EmptyState icon="inbox" title="No results" message="No passages match these filters. Try a wider range or a different operator." />}

        {status === 'ready' && mode === 'byOperator' && <ByOperatorResult op={op} range={range} chart={chart} />}
        {status === 'ready' && mode === 'pair' && <PairResult op={op} tagOp={tagOp} range={range} data={data} />}
        {status === 'ready' && mode === 'station' && <StationResult stationId={stationId} range={range} data={data} />}
      </div>
    </>
  );
}

function ResultTitle({ title, sub }) {
  return (
    <div className="anx-rtitle">
      <h2>{title}</h2>
      <span>{sub}</span>
    </div>
  );
}

function ByOperatorResult({ op, range, chart }) {
  const totalPasses = chart.reduce((s, r) => s + r.passes, 0);
  const totalCost = chart.reduce((s, r) => s + r.cost, 0);
  if (!chart.length) {
    return <EmptyState title="No cross-operator activity" message="No visiting-operator passages were charged for this operator in the period." />;
  }
  return (
    <>
      <div className="anx-rhead">
        <ResultTitle title={OP_LABEL[op] || op} sub={`${range.from} → ${range.to}`} />
        <Button
          size="sm" variant="secondary" icon="download"
          onClick={() => downloadCsv(`chargesBy_${op}_${range.from}_${range.to}.csv`,
            toCsv(chart.map((r) => ({ operator: r.name, passages: r.passes, charge_eur: r.cost.toFixed(2) })), ['operator', 'passages', 'charge_eur']))}
        >CSV</Button>
      </div>

      <div className="anx-summary">
        <StatCard label="Visiting operators" value={chart.length} />
        <StatCard label="Cross-operator passages" value={num(totalPasses)} />
        <StatCard label="Total charged" value={money(totalCost)} hint="Owed by visiting operators" />
      </div>

      <p className="anx-viz-cap">Charges by visiting operator</p>
      <div className="anx-viz scroll-x">
        <ResponsiveContainer width="100%" height={320} minWidth={360}>
          <BarChart data={chart} layout="vertical" margin={{ top: 4, right: 56, bottom: 4, left: 8 }}>
            <CartesianGrid strokeDasharray="2 4" stroke="var(--chart-grid)" horizontal={false} />
            <XAxis type="number" tick={{ fill: 'var(--chart-axis)', fontSize: 11 }} tickLine={false} axisLine={false} tickFormatter={(v) => `€${v}`} />
            <YAxis type="category" dataKey="name" width={120} tick={{ fill: 'var(--color-text-muted)', fontSize: 12 }} tickLine={false} axisLine={{ stroke: 'var(--chart-grid)' }} />
            <Tooltip cursor={{ fill: 'rgba(11,37,69,0.05)' }} formatter={(v) => [money(v), 'Charge']} />
            <Bar dataKey="cost" radius={[0, 3, 3, 0]} maxBarSize={26}>
              <LabelList dataKey="cost" position="right" formatter={(v) => money(v)} style={{ fill: 'var(--color-text-muted)', fontSize: 11, fontWeight: 600 }} />
              {chart.map((r) => <Cell key={r.op} fill={operatorColor(r.op)} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      <div className="scroll-x anx-tablewrap">
        <table className="ui-table">
          <thead><tr><th>Visiting operator</th><th className="num">Passages</th><th className="num">Charge</th></tr></thead>
          <tbody>
            {chart.map((r) => (
              <tr key={r.op}>
                <td><span className="anx-swatch" style={{ background: operatorColor(r.op) }} />{r.name}</td>
                <td className="num">{num(r.passes)}</td>
                <td className="num">{money(r.cost)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}

function PairResult({ op, tagOp, range, data }) {
  const list = Array.isArray(data.passList) ? data.passList : [];
  const totalCharge = list.reduce((s, p) => s + (Number(p.passCharge) || 0), 0);
  return (
    <>
      <div className="anx-rhead">
        <ResultTitle title={`${OP_LABEL[op] || op} ← ${OP_LABEL[tagOp] || tagOp}`} sub={`${range.from} → ${range.to}`} />
        {list.length > 0 && (
          <Button size="sm" variant="secondary" icon="download"
            onClick={() => downloadCsv(`passAnalysis_${op}_${tagOp}_${range.from}_${range.to}.csv`,
              toCsv(list.map((p) => ({ pass_id: p.passID, station: p.stationID, timestamp: p.timestamp, tag: p.tagID, charge_eur: Number(p.passCharge).toFixed(2) })), ['pass_id', 'station', 'timestamp', 'tag', 'charge_eur']))}
          >CSV</Button>
        )}
      </div>
      <div className="anx-summary">
        <StatCard label="Passages" value={num(data.nPasses ?? list.length)} hint={`${tagOp} tags at ${op} stations`} />
        <StatCard label="Total charge" value={money(totalCharge)} />
        <StatCard label="Period" value={`${range.from.slice(5)} – ${range.to.slice(5)}`} hint={range.from.slice(0, 4)} />
      </div>
      {list.length === 0 ? (
        <EmptyState title="No passages" message="No passages between this operator pair in the period." />
      ) : (
        <div className="scroll-x anx-tablewrap anx-tablewrap--tall">
          <table className="ui-table">
            <thead><tr><th>#</th><th>Station</th><th>Timestamp</th><th>Tag</th><th className="num">Charge</th></tr></thead>
            <tbody>
              {list.slice(0, 250).map((p) => (
                <tr key={p.passID}><td>{p.passIndex}</td><td>{p.stationID}</td><td>{p.timestamp}</td><td>{p.tagID}</td><td className="num">{money(p.passCharge)}</td></tr>
              ))}
            </tbody>
          </table>
          {list.length > 250 && <p className="anx-more">First 250 of {list.length} — export the CSV for the full list.</p>}
        </div>
      )}
    </>
  );
}

function StationResult({ stationId, range, data }) {
  const list = Array.isArray(data.passList) ? data.passList : [];
  const homeCount = list.filter((p) => p.passType === 'home').length;
  const totalCharge = list.reduce((s, p) => s + (Number(p.passCharge) || 0), 0);
  return (
    <>
      <div className="anx-rhead">
        <ResultTitle title={`Station ${stationId.toUpperCase()}`} sub={`${range.from} → ${range.to}`} />
        {list.length > 0 && (
          <Button size="sm" variant="secondary" icon="download"
            onClick={() => downloadCsv(`station_${stationId}_${range.from}_${range.to}.csv`,
              toCsv(list.map((p) => ({ pass_id: p.passID, timestamp: p.timestamp, tag: p.tagID, provider: p.tagProvider, type: p.passType, charge_eur: Number(p.passCharge).toFixed(2) })), ['pass_id', 'timestamp', 'tag', 'provider', 'type', 'charge_eur']))}
          >CSV</Button>
        )}
      </div>
      <div className="anx-summary">
        <StatCard label="Passages" value={num(list.length)} />
        <StatCard label="Home / visitor" value={`${homeCount} / ${list.length - homeCount}`} hint="Own tags / visiting tags" />
        <StatCard label="Total charge" value={money(totalCharge)} />
      </div>
      {list.length === 0 ? (
        <EmptyState title="No passages" message="No passages at this station in the period. Check the station ID." />
      ) : (
        <div className="scroll-x anx-tablewrap anx-tablewrap--tall">
          <table className="ui-table">
            <thead><tr><th>#</th><th>Timestamp</th><th>Tag</th><th>Provider</th><th>Type</th><th className="num">Charge</th></tr></thead>
            <tbody>
              {list.slice(0, 250).map((p) => (
                <tr key={p.passID}><td>{p.passIndex}</td><td>{p.timestamp}</td><td>{p.tagID}</td><td>{p.tagProvider}</td><td>{p.passType}</td><td className="num">{money(p.passCharge)}</td></tr>
              ))}
            </tbody>
          </table>
          {list.length > 250 && <p className="anx-more">First 250 of {list.length} — export the CSV for the full list.</p>}
        </div>
      )}
    </>
  );
}
